package net.bible.code.data.jpa;
// Generated Jan 25, 2020 6:04:54 PM by Hibernate Tools 4.3.4.Final


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BcScrollLookup generated by hbm2java
 */
@Entity
@Table(name="bc_scroll_lookup"
    ,catalog="nanzopco_torah"
)
public class BcScrollLookup  implements java.io.Serializable {


     private Integer id;
     private BcScroll bcScroll;
     private TorahBook torahBook;
     private Integer chapter;
     private Integer verseX;
     private Integer verseY;
     private String createdBy;
     private Date createdDate;
     private String modifiedBy;
     private Date modifiedDate;
     private String crossRef;

    public BcScrollLookup() {
    }

	
    public BcScrollLookup(String createdBy, Date createdDate) {
        this.createdBy = createdBy;
        this.createdDate = createdDate;
    }
    public BcScrollLookup(BcScroll bcScroll, TorahBook torahBook, Integer chapter, Integer verseX, Integer verseY, String createdBy, Date createdDate, String modifiedBy, Date modifiedDate, String crossRef) {
       this.bcScroll = bcScroll;
       this.torahBook = torahBook;
       this.chapter = chapter;
       this.verseX = verseX;
       this.verseY = verseY;
       this.createdBy = createdBy;
       this.createdDate = createdDate;
       this.modifiedBy = modifiedBy;
       this.modifiedDate = modifiedDate;
       this.crossRef = crossRef;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="scroll_id")
    public BcScroll getBcScroll() {
        return this.bcScroll;
    }
    
    public void setBcScroll(BcScroll bcScroll) {
        this.bcScroll = bcScroll;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="book_id")
    public TorahBook getTorahBook() {
        return this.torahBook;
    }
    
    public void setTorahBook(TorahBook torahBook) {
        this.torahBook = torahBook;
    }

    
    @Column(name="chapter")
    public Integer getChapter() {
        return this.chapter;
    }
    
    public void setChapter(Integer chapter) {
        this.chapter = chapter;
    }

    
    @Column(name="verse_x")
    public Integer getVerseX() {
        return this.verseX;
    }
    
    public void setVerseX(Integer verseX) {
        this.verseX = verseX;
    }

    
    @Column(name="verse_y")
    public Integer getVerseY() {
        return this.verseY;
    }
    
    public void setVerseY(Integer verseY) {
        this.verseY = verseY;
    }

    
    @Column(name="created_by", nullable=false, length=45)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_date", nullable=false, length=19)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    
    @Column(name="modified_by", length=45)
    public String getModifiedBy() {
        return this.modifiedBy;
    }
    
    public void setModifiedBy(String modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="modified_date", length=19)
    public Date getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }

    
    @Column(name="cross_ref", length=1)
    public String getCrossRef() {
        return this.crossRef;
    }
    
    public void setCrossRef(String crossRef) {
        this.crossRef = crossRef;
    }




}


