package net.bible.code.data.jpa;
// Generated Jan 25, 2020 6:04:54 PM by Hibernate Tools 4.3.4.Final


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BcScroll generated by hbm2java
 */
@Entity
@Table(name="bc_scroll"
    ,catalog="nanzopco_torah"
)
public class BcScroll  implements java.io.Serializable {


     private Integer id;
     private TorahBook torahBook;
     private String title;
     private String age;
     private String createdBy;
     private Date createdDate;
     private String modifiedBy;
     private Date modifiedDate;
     private String verseAddress;
     private String orgin;
     private String material;
     private String imageUrl;
     private String imageUrl2;
     private Set<BcScrollLookup> bcScrollLookups = new HashSet<BcScrollLookup>(0);
     private Set<BcScrollImage> bcScrollImages = new HashSet<BcScrollImage>(0);
     private Set<BcScrollVerse> bcScrollVerses = new HashSet<BcScrollVerse>(0);

    public BcScroll() {
    }

	
    public BcScroll(String createdBy, Date createdDate) {
        this.createdBy = createdBy;
        this.createdDate = createdDate;
    }
    public BcScroll(TorahBook torahBook, String title, String age, String createdBy, Date createdDate, String modifiedBy, Date modifiedDate, String verseAddress, String orgin, String material, String imageUrl, String imageUrl2, Set<BcScrollLookup> bcScrollLookups, Set<BcScrollImage> bcScrollImages, Set<BcScrollVerse> bcScrollVerses) {
       this.torahBook = torahBook;
       this.title = title;
       this.age = age;
       this.createdBy = createdBy;
       this.createdDate = createdDate;
       this.modifiedBy = modifiedBy;
       this.modifiedDate = modifiedDate;
       this.verseAddress = verseAddress;
       this.orgin = orgin;
       this.material = material;
       this.imageUrl = imageUrl;
       this.imageUrl2 = imageUrl2;
       this.bcScrollLookups = bcScrollLookups;
       this.bcScrollImages = bcScrollImages;
       this.bcScrollVerses = bcScrollVerses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="book_id")
    public TorahBook getTorahBook() {
        return this.torahBook;
    }
    
    public void setTorahBook(TorahBook torahBook) {
        this.torahBook = torahBook;
    }

    
    @Column(name="title", length=100)
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }

    
    @Column(name="age", length=45)
    public String getAge() {
        return this.age;
    }
    
    public void setAge(String age) {
        this.age = age;
    }

    
    @Column(name="created_by", nullable=false, length=45)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_date", nullable=false, length=19)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    
    @Column(name="modified_by", length=45)
    public String getModifiedBy() {
        return this.modifiedBy;
    }
    
    public void setModifiedBy(String modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="modified_date", length=19)
    public Date getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }

    
    @Column(name="verse_address", length=50)
    public String getVerseAddress() {
        return this.verseAddress;
    }
    
    public void setVerseAddress(String verseAddress) {
        this.verseAddress = verseAddress;
    }

    
    @Column(name="orgin", length=50)
    public String getOrgin() {
        return this.orgin;
    }
    
    public void setOrgin(String orgin) {
        this.orgin = orgin;
    }

    
    @Column(name="material", length=100)
    public String getMaterial() {
        return this.material;
    }
    
    public void setMaterial(String material) {
        this.material = material;
    }

    
    @Column(name="image_url", length=500)
    public String getImageUrl() {
        return this.imageUrl;
    }
    
    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }

    
    @Column(name="image_url2", length=500)
    public String getImageUrl2() {
        return this.imageUrl2;
    }
    
    public void setImageUrl2(String imageUrl2) {
        this.imageUrl2 = imageUrl2;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="bcScroll")
    public Set<BcScrollLookup> getBcScrollLookups() {
        return this.bcScrollLookups;
    }
    
    public void setBcScrollLookups(Set<BcScrollLookup> bcScrollLookups) {
        this.bcScrollLookups = bcScrollLookups;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="bcScroll")
    public Set<BcScrollImage> getBcScrollImages() {
        return this.bcScrollImages;
    }
    
    public void setBcScrollImages(Set<BcScrollImage> bcScrollImages) {
        this.bcScrollImages = bcScrollImages;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="bcScroll")
    public Set<BcScrollVerse> getBcScrollVerses() {
        return this.bcScrollVerses;
    }
    
    public void setBcScrollVerses(Set<BcScrollVerse> bcScrollVerses) {
        this.bcScrollVerses = bcScrollVerses;
    }




}


