package net.bible.code.data.jpa;
// Generated Jan 25, 2020 6:04:54 PM by Hibernate Tools 4.3.4.Final


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BcScrollImage generated by hbm2java
 */
@Entity
@Table(name="bc_scroll_image"
    ,catalog="nanzopco_torah"
)
public class BcScrollImage  implements java.io.Serializable {


     private Integer id;
     private BcScroll bcScroll;
     private String imageUrl;
     private String createdBy;
     private Date createdDate;
     private String modifiedBy;
     private Date modifiedDate;

    public BcScrollImage() {
    }

	
    public BcScrollImage(String createdBy, Date createdDate) {
        this.createdBy = createdBy;
        this.createdDate = createdDate;
    }
    public BcScrollImage(BcScroll bcScroll, String imageUrl, String createdBy, Date createdDate, String modifiedBy, Date modifiedDate) {
       this.bcScroll = bcScroll;
       this.imageUrl = imageUrl;
       this.createdBy = createdBy;
       this.createdDate = createdDate;
       this.modifiedBy = modifiedBy;
       this.modifiedDate = modifiedDate;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="scroll_id")
    public BcScroll getBcScroll() {
        return this.bcScroll;
    }
    
    public void setBcScroll(BcScroll bcScroll) {
        this.bcScroll = bcScroll;
    }

    
    @Column(name="image_url", length=500)
    public String getImageUrl() {
        return this.imageUrl;
    }
    
    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }

    
    @Column(name="created_by", nullable=false, length=45)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_date", nullable=false, length=19)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    
    @Column(name="modified_by", length=45)
    public String getModifiedBy() {
        return this.modifiedBy;
    }
    
    public void setModifiedBy(String modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="modified_date", length=19)
    public Date getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }




}


