package net.bible.code.data.jpa;
// Generated Jan 25, 2020 6:04:54 PM by Hibernate Tools 4.3.4.Final


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TorahBook generated by hbm2java
 */
@Entity
@Table(name="torah_book"
    ,catalog="nanzopco_torah"
)
public class TorahBook  implements java.io.Serializable {


     private Integer id;
     private String bookName;
     private String engBookName;
     private String tranBookName;
     private Set<BcScrollLookup> bcScrollLookups = new HashSet<BcScrollLookup>(0);
     private Set<BcScroll> bcScrolls = new HashSet<BcScroll>(0);
     private Set<TorahVerse> torahVerses = new HashSet<TorahVerse>(0);
     private Set<BcScrollVerse> bcScrollVerses = new HashSet<BcScrollVerse>(0);

    public TorahBook() {
    }

    public TorahBook(String bookName, String engBookName, String tranBookName, Set<BcScrollLookup> bcScrollLookups, Set<BcScroll> bcScrolls, Set<TorahVerse> torahVerses, Set<BcScrollVerse> bcScrollVerses) {
       this.bookName = bookName;
       this.engBookName = engBookName;
       this.tranBookName = tranBookName;
       this.bcScrollLookups = bcScrollLookups;
       this.bcScrolls = bcScrolls;
       this.torahVerses = torahVerses;
       this.bcScrollVerses = bcScrollVerses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="book_name", length=50)
    public String getBookName() {
        return this.bookName;
    }
    
    public void setBookName(String bookName) {
        this.bookName = bookName;
    }

    
    @Column(name="eng_book_name", length=50)
    public String getEngBookName() {
        return this.engBookName;
    }
    
    public void setEngBookName(String engBookName) {
        this.engBookName = engBookName;
    }

    
    @Column(name="tran_book_name", length=50)
    public String getTranBookName() {
        return this.tranBookName;
    }
    
    public void setTranBookName(String tranBookName) {
        this.tranBookName = tranBookName;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="torahBook")
    public Set<BcScrollLookup> getBcScrollLookups() {
        return this.bcScrollLookups;
    }
    
    public void setBcScrollLookups(Set<BcScrollLookup> bcScrollLookups) {
        this.bcScrollLookups = bcScrollLookups;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="torahBook")
    public Set<BcScroll> getBcScrolls() {
        return this.bcScrolls;
    }
    
    public void setBcScrolls(Set<BcScroll> bcScrolls) {
        this.bcScrolls = bcScrolls;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="torahBook")
    public Set<TorahVerse> getTorahVerses() {
        return this.torahVerses;
    }
    
    public void setTorahVerses(Set<TorahVerse> torahVerses) {
        this.torahVerses = torahVerses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="torahBook")
    public Set<BcScrollVerse> getBcScrollVerses() {
        return this.bcScrollVerses;
    }
    
    public void setBcScrollVerses(Set<BcScrollVerse> bcScrollVerses) {
        this.bcScrollVerses = bcScrollVerses;
    }




}


