package net.bible.code.data.jpa;
// Generated Jan 25, 2020 6:04:54 PM by Hibernate Tools 4.3.4.Final


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TorahVerse generated by hbm2java
 */
@Entity
@Table(name="torah_verse"
    ,catalog="nanzopco_torah"
)
public class TorahVerse  implements java.io.Serializable {


     private Integer id;
     private TorahBook torahBook;
     private String verse;
     private String engVerse;
     private String tranVerse;
     private int numChapter;
     private int numVerse;
     private String createdBy;
     private Date createdDate;
     private String modifedBy;
     private Date modifiedDate;
     private String HChapter;
     private String HVerse;
     private Integer numValue;
     private Set<TorahVerseWord> torahVerseWords = new HashSet<TorahVerseWord>(0);

    public TorahVerse() {
    }

	
    public TorahVerse(TorahBook torahBook, int numChapter, int numVerse, String createdBy, Date createdDate) {
        this.torahBook = torahBook;
        this.numChapter = numChapter;
        this.numVerse = numVerse;
        this.createdBy = createdBy;
        this.createdDate = createdDate;
    }
    public TorahVerse(TorahBook torahBook, String verse, String engVerse, String tranVerse, int numChapter, int numVerse, String createdBy, Date createdDate, String modifedBy, Date modifiedDate, String HChapter, String HVerse, Integer numValue, Set<TorahVerseWord> torahVerseWords) {
       this.torahBook = torahBook;
       this.verse = verse;
       this.engVerse = engVerse;
       this.tranVerse = tranVerse;
       this.numChapter = numChapter;
       this.numVerse = numVerse;
       this.createdBy = createdBy;
       this.createdDate = createdDate;
       this.modifedBy = modifedBy;
       this.modifiedDate = modifiedDate;
       this.HChapter = HChapter;
       this.HVerse = HVerse;
       this.numValue = numValue;
       this.torahVerseWords = torahVerseWords;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="book_id", nullable=false)
    public TorahBook getTorahBook() {
        return this.torahBook;
    }
    
    public void setTorahBook(TorahBook torahBook) {
        this.torahBook = torahBook;
    }

    
    @Column(name="verse", length=600)
    public String getVerse() {
        return this.verse;
    }
    
    public void setVerse(String verse) {
        this.verse = verse;
    }

    
    @Column(name="eng_verse", length=600)
    public String getEngVerse() {
        return this.engVerse;
    }
    
    public void setEngVerse(String engVerse) {
        this.engVerse = engVerse;
    }

    
    @Column(name="tran_verse", length=600)
    public String getTranVerse() {
        return this.tranVerse;
    }
    
    public void setTranVerse(String tranVerse) {
        this.tranVerse = tranVerse;
    }

    
    @Column(name="num_chapter", nullable=false)
    public int getNumChapter() {
        return this.numChapter;
    }
    
    public void setNumChapter(int numChapter) {
        this.numChapter = numChapter;
    }

    
    @Column(name="num_verse", nullable=false)
    public int getNumVerse() {
        return this.numVerse;
    }
    
    public void setNumVerse(int numVerse) {
        this.numVerse = numVerse;
    }

    
    @Column(name="created_by", nullable=false, length=45)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_date", nullable=false, length=19)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    
    @Column(name="modifed_by", length=45)
    public String getModifedBy() {
        return this.modifedBy;
    }
    
    public void setModifedBy(String modifedBy) {
        this.modifedBy = modifedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="modified_date", length=19)
    public Date getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }

    
    @Column(name="h_chapter", length=45)
    public String getHChapter() {
        return this.HChapter;
    }
    
    public void setHChapter(String HChapter) {
        this.HChapter = HChapter;
    }

    
    @Column(name="h_verse", length=45)
    public String getHVerse() {
        return this.HVerse;
    }
    
    public void setHVerse(String HVerse) {
        this.HVerse = HVerse;
    }

    
    @Column(name="num_value")
    public Integer getNumValue() {
        return this.numValue;
    }
    
    public void setNumValue(Integer numValue) {
        this.numValue = numValue;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="torahVerse")
    public Set<TorahVerseWord> getTorahVerseWords() {
        return this.torahVerseWords;
    }
    
    public void setTorahVerseWords(Set<TorahVerseWord> torahVerseWords) {
        this.torahVerseWords = torahVerseWords;
    }




}


