package net.bible.code.data.jpa;
// Generated Jan 25, 2020 6:04:54 PM by Hibernate Tools 4.3.4.Final


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TorahVerseWord generated by hbm2java
 */
@Entity
@Table(name="torah_verse_word"
    ,catalog="nanzopco_torah"
)
public class TorahVerseWord  implements java.io.Serializable {


     private Integer id;
     private TorahVerse torahVerse;
     private String word;
     private String tranWord;
     private Integer numValue;
     private Integer numIndex;
     private String createdBy;
     private Date createdDate;
     private String modifiedBy;
     private Date modifiedDate;
     private String engTranslation;
     private String wordNv;
     private String strongUsage;
     private String strongMeaning;

    public TorahVerseWord() {
    }

	
    public TorahVerseWord(TorahVerse torahVerse, String createdBy, Date createdDate) {
        this.torahVerse = torahVerse;
        this.createdBy = createdBy;
        this.createdDate = createdDate;
    }
    public TorahVerseWord(TorahVerse torahVerse, String word, String tranWord, Integer numValue, Integer numIndex, String createdBy, Date createdDate, String modifiedBy, Date modifiedDate, String engTranslation, String wordNv, String strongUsage, String strongMeaning) {
       this.torahVerse = torahVerse;
       this.word = word;
       this.tranWord = tranWord;
       this.numValue = numValue;
       this.numIndex = numIndex;
       this.createdBy = createdBy;
       this.createdDate = createdDate;
       this.modifiedBy = modifiedBy;
       this.modifiedDate = modifiedDate;
       this.engTranslation = engTranslation;
       this.wordNv = wordNv;
       this.strongUsage = strongUsage;
       this.strongMeaning = strongMeaning;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="verse_id", nullable=false)
    public TorahVerse getTorahVerse() {
        return this.torahVerse;
    }
    
    public void setTorahVerse(TorahVerse torahVerse) {
        this.torahVerse = torahVerse;
    }

    
    @Column(name="word", length=45)
    public String getWord() {
        return this.word;
    }
    
    public void setWord(String word) {
        this.word = word;
    }

    
    @Column(name="tran_word", length=45)
    public String getTranWord() {
        return this.tranWord;
    }
    
    public void setTranWord(String tranWord) {
        this.tranWord = tranWord;
    }

    
    @Column(name="num_value")
    public Integer getNumValue() {
        return this.numValue;
    }
    
    public void setNumValue(Integer numValue) {
        this.numValue = numValue;
    }

    
    @Column(name="num_index")
    public Integer getNumIndex() {
        return this.numIndex;
    }
    
    public void setNumIndex(Integer numIndex) {
        this.numIndex = numIndex;
    }

    
    @Column(name="created_by", nullable=false, length=45)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_date", nullable=false, length=19)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    
    @Column(name="modified_by", length=45)
    public String getModifiedBy() {
        return this.modifiedBy;
    }
    
    public void setModifiedBy(String modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="modified_date", length=19)
    public Date getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }

    
    @Column(name="eng_translation", length=300)
    public String getEngTranslation() {
        return this.engTranslation;
    }
    
    public void setEngTranslation(String engTranslation) {
        this.engTranslation = engTranslation;
    }

    
    @Column(name="word_nv", length=45)
    public String getWordNv() {
        return this.wordNv;
    }
    
    public void setWordNv(String wordNv) {
        this.wordNv = wordNv;
    }

    
    @Column(name="strong_usage", length=800)
    public String getStrongUsage() {
        return this.strongUsage;
    }
    
    public void setStrongUsage(String strongUsage) {
        this.strongUsage = strongUsage;
    }

    
    @Column(name="strong_meaning", length=400)
    public String getStrongMeaning() {
        return this.strongMeaning;
    }
    
    public void setStrongMeaning(String strongMeaning) {
        this.strongMeaning = strongMeaning;
    }




}


